### ISSUE TITLE
Support `*` in workspace members

### ISSUE THREAD

**Issue by Stupremee** [yusdacra/nix-cargo-integration#10]
```toml
[workspace]
members = [
  "crates/*",
]
```

A `Cargo.toml` like this is very common and much nicer to use than to list every crate, however, `nix-cargo-integration` currently fails with
```
'/nix/store/v7nikwxvxcs9brviravwal66r2b2ivwg-source/crates/*': No such file or directory
```
if you try to use `*`.

It would be nice to have support for glob paths.
