### ISSUE TITLE
attribute packages is missing

### ISSUE THREAD

**Issue by yavko** [yusdacra/nix-cargo-integration#103]
Idk why but it says packages is missing? idk

<details>
<summary>Trace</summary>

```
error: attribute 'packages' missing

       at /nix/store/xla5whhibb8b3gnbfidic1kcj9yy5lbg-source/src/build/default.nix:209:22:

          208|   _outputs = l.dbgX "outputs" (utils.mkCrateOutputs baseConfig);
          209|   unwrappedPackage = _outputs.packages.${cargoPkg.name};
             |                      ^
          210|   shell = _outputs.devShells.${cargoPkg.name};

       … while evaluating anonymous lambda

       at /nix/store/xla5whhibb8b3gnbfidic1kcj9yy5lbg-source/src/build/default.nix:215:8:

          214|     wrapped = l.pipe unwrappedPackage [
          215|       (old:
             |        ^
          216|         old

       … from call site

       at /nix/store/lwnrrndriqm2d588lgd6184bcawj3b0z-source/lib/trivial.nix:62:30:

           61|   pipe = val: functions:
           62|     let reverseApply = x: f: f x;
             |                              ^
           63|     in builtins.foldl' reverseApply val functions;

       … while evaluating 'reverseApply'

       at /nix/store/lwnrrndriqm2d588lgd6184bcawj3b0z-source/lib/trivial.nix:62:27:

           61|   pipe = val: functions:
           62|     let reverseApply = x: f: f x;
             |                           ^
           63|     in builtins.foldl' reverseApply val functions;

       … from call site

       at /nix/store/lwnrrndriqm2d588lgd6184bcawj3b0z-source/lib/trivial.nix:63:8:

           62|     let reverseApply = x: f: f x;
           63|     in builtins.foldl' reverseApply val functions;
             |        ^
           64|

       … while evaluating 'pipe'

       at /nix/store/lwnrrndriqm2d588lgd6184bcawj3b0z-source/lib/trivial.nix:61:15:

           60|   */
           61|   pipe = val: functions:
             |               ^
           62|     let reverseApply = x: f: f x;

       … from call site

       at /nix/store/xla5whhibb8b3gnbfidic1kcj9yy5lbg-source/src/build/default.nix:214:15:

          213|   package = let
          214|     wrapped = l.pipe unwrappedPackage [
             |               ^
          215|       (old:

       … while evaluating the attribute 'package'

       at /nix/store/xla5whhibb8b3gnbfidic1kcj9yy5lbg-source/src/build/default.nix:213:3:

          212|   config = baseConfig // {inherit profile features doCheck;};
          213|   package = let
             |   ^
          214|     wrapped = l.pipe unwrappedPackage [

       … while evaluating anonymous lambda

       at /nix/store/xla5whhibb8b3gnbfidic1kcj9yy5lbg-source/src/makeOutput.nix:119:30:

          118|   # Packages set to be put in the outputs.
          119|   _packages = l.mapAttrs (_: v: v.package) packagesRaw;
             |                              ^
          120|   packages = {

       … from call site

       … while evaluating anonymous lambda

       at /nix/store/xla5whhibb8b3gnbfidic1kcj9yy5lbg-source/src/shell.nix:1:1:

            1| {
             | ^
            2|   common,

       … from call site

       at /nix/store/xla5whhibb8b3gnbfidic1kcj9yy5lbg-source/src/makeOutput.nix:154:25:

          153|   devShells = {
          154|     ${system}.${name} = mkShell {
             |                         ^
          155|       inherit common;

       … while evaluating 'mergeShells'

       at /nix/store/xla5whhibb8b3gnbfidic1kcj9yy5lbg-source/src/makeOutputs.nix:144:17:

          143|
          144|   mergeShells = shellAttrs: let
             |                 ^
          145|     shells = l.attrValues shellAttrs;

       … from call site

       at /nix/store/xla5whhibb8b3gnbfidic1kcj9yy5lbg-source/src/makeOutputs.nix:187:32:

          186|         l.mapAttrs
          187|         (_: s: s // {default = mergeShells s;})
             |                                ^
          188|         combinedOutputs.devShells;

```

</details>

And the code is:
```nix
{
  description = "dev shell";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
		rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    nci.url = "github:yusdacra/nix-cargo-integration";
    nci.inputs.nixpkgs.follows = "nixpkgs";
		nci.inputs.rust-overlay.follows = "rust-overlay";
  };

  outputs = { nci, ...}: 
    nci.lib.makeOutputs {
      root = ./.;
      config = common: {
        shell = {
          packages = with common.pkgs; [ rust-analyzer wasm-pack ];
        };
      };
    };
}
```

```toml
[package]
name = "cf-analytics"
version = "0.1.0"
authors = ["yavko <yavornkolev@gmail.com>"]
edition = "2021"

[package.metadata.nix]
build = true
#systems = ["wasm32-unknown-unknown"]

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.6", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.5", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
```
