### ISSUE TITLE
Doesn't work with workspace package settings

### ISSUE THREAD

**Issue by yavko** [yusdacra/nix-cargo-integration#123]
So I'm setting this
```toml
[workspace.package]
version = "0.3.2"
license = "GPL-3.0-or-later"
repository = "https://github.com/hyprland-community/hyprland-rs"
keywords = ["hyprland", "ipc", "hypr", "wayland", "linux"]
categories = ["api-bindings"]
authors = ["yavko <yavornkolev@gmail.com>"]
```
and referencing it here
```toml
[package]
name = "hyprland"
edition = "2021"
readme = "README.md"
description = "A unoffical rust wrapper for hyprland's IPC"
homepage = "https://github.com/hyprland-community/hyprland-rs"
version.workspace = true
license.workspace = true
author.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
```

but I'm and getting this error
![image](https://user-images.githubusercontent.com/15178513/236649315-27141980-1e97-4317-baaf-88d964860cec.png)

So it seems like it needs to be able to reference workspace settings.
