### ISSUE TITLE
Overlaying rust-bin

### ISSUE THREAD

**Issue by NickHu** [yusdacra/nix-cargo-integration#60]
Is it possible to globally overlay rustc, rustfmt, cargo, etc. for the dev shell and the build environment? I tried to use https://github.com/yusdacra/nix-cargo-integration/blob/master/docs/example_flake.nix#L39 but I wasn't very successful.

In particular, I am interested in using a version of rustc which has the `wasm32-unknown-unknown` target, e.g. from https://github.com/oxalica/rust-overlay.

**Comment by yusdacra** [comment]
If you are trying to add a target, you should use a [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) file. In your case, this can look like this:
```toml
[toolchain]
channel = "nightly-2022-03-05" # or whatever channel you are using
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
```

There isn't yet a way to directly override what toolchain `nix-cargo-integration` will use, as I haven't yet thought of a good way to expose this. Once #56 is merged, I can work on this more.
