### ISSUE TITLE
Optional dependencies cause build failures when incompatible

### ISSUE THREAD

**Issue by khrj** [yusdacra/nix-cargo-integration#67]
Any project with the `reqwest` crate as a dependency fails to build on linux because it optionally depends on `MacOS_SDK-10.12`

```
❯ nix build
error: Package ‘MacOS_SDK-10.12’ in /nix/store/hsff9pi1qinxljahr833z0xivr1apx27-source/pkgs/os-specific/darwin/apple-sdk/default.nix:50 is not supported on ‘x86_64-linux’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environmentvariable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

[Minimal reproducible example](https://github.com/KhushrajSandbox/nix-cargo-integration-optional-deps)

**Comment by khrj** [comment]
From what I understand, this is caused by `reqwest`'s `default-tls` feature, which adds a dependency on [`native-tls`](https://github.com/sfackler/rust-native-tls), which depends on `security-framework`, but only when building for macOS. `security-framework` provides bindings for the MacOS SDK's Security.framework

`native-tls`'s `Cargo.toml` (irrelevant sections removed):

```toml
[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
security-framework = "2.0.0"
security-framework-sys = "2.0.0"

[target.'cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))'.dependencies]
openssl = "0.10.29"
openssl-sys = "0.9.55"
openssl-probe = "0.1"

[target.'cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))'.build_dependencies]
openssl-src = { version = "300.0.3", optional = true }
```

Adding just `native-tls` to `Cargo.toml` instead of `reqwest` produces a similar error:

```toml
native-tls = "0.2"
```

```
error: Package ‘MacOS_SDK-10.12’ in /nix/store/hsff9pi1qinxljahr833z0xivr1apx27-source/pkgs/os-specific/darwin/apple-sdk/default.nix:50 is not supported on ‘x86_64-linux’, refusing to evaluate.
...
```
